spring.application.name=consumer
server.port=8081

# Kafka Consumer Config
notification.kafka.topic=notification-topic

# OCI Kafka Connection
spring.kafka.bootstrap-servers=<TU-BOOTSTRAP-SERVER-DE-OCI>:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-512
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="<TU-USERNAME>" password="<TU-PASSWORD>";
