spring.application.name=consumer
server.port=8081

# Kafka Consumer Config
spring.kafka.bootstrap-servers=localhost:9092
notification.kafka.topic=notification-topic
spring.kafka.consumer.group-id=notification-group

# Leer desde el inicio si es la primera vez
spring.kafka.consumer.auto-offset-reset=earliest
