spring.application.name=producer
server.port=8080

# Kafka Producer Config
notification.kafka.topic=notification-topic
spring.kafka.bootstrap-servers=localhost:9092

# Auto-crear topics si no existen
spring.kafka.producer.properties.auto.create.topics.enable=true
